# Generated by Django 4.1.7 on 2023-03-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_images', models.ImageField(upload_to='profile_image')),
                ('project_images', models.ImageField(upload_to='project_images')),
            ],
        ),
    ]
