# Generated by Django 4.1.7 on 2023-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_profileimages_projectimages_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_images', models.ImageField(upload_to='poster_images')),
            ],
        ),
    ]
