# Generated by Django 4.1.7 on 2023-03-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_posterimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='description',
            field=models.TextField(db_column='About', null=True),
        ),
    ]
