# Generated by Django 4.1.7 on 2023-03-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_projectimages_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
